///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: sfx.aks
/// Generation time: Tue, May 19, 2020 23:44:32
///

/// Song 'g_music' metadata macros
#define g_sfx_address  0x0810
#define g_sfx_size     168
#define g_sfx_end      0x8b7

/// Song 'g_music' array declaration
extern void g_sfx[g_sfx_size];
